version: "3.7"

services:
  my-app:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "1001:80"
